services:
  - type: web
    name: dialogengine-v2
    env: node
    region: frankfurt
    buildCommand: rm -rf node_modules && rm -rf .next && npm cache clean --force && npm install && npm install tailwindcss@3.4.1 --force && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: dialogengine-db
          property: connectionString
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: LUNARY_PUBLIC_KEY
        sync: false
    autoDeploy: true

databases:
  - name: dialogengine-db
    databaseName: dialogengine
    region: frankfurt
    plan: free
    postgresMajorVersion: "14"
    ipAllowList: [] 