services:
  - type: web
    name: dialogengine-v2
    env: node
    region: frankfurt
    buildCommand: |
      rm -rf node_modules && rm -rf .next && npm cache clean --force
      npm install -g tailwindcss@3.4.1 postcss@8.4.35 postcss-import@15.1.0 autoprefixer@10.4.17
      npm install
      # Backup für globals.css falls der Import fehlschlägt
      cat > src/app/globals.css.backup << EOL
      @tailwind base;
      @tailwind components;
      @tailwind utilities;
      EOL
      # Versuche zu bauen, ersetze globals.css wenn es fehlschlägt
      npm run build || (cp src/app/globals.css.backup src/app/globals.css && npm run build)
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: dialogengine-db
          property: connectionString
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: LUNARY_PUBLIC_KEY
        sync: false
    autoDeploy: true

databases:
  - name: dialogengine-db
    databaseName: dialogengine
    region: frankfurt
    plan: free
    postgresMajorVersion: "14"
    ipAllowList: [] 